// q4-vue/pages/books.vue
<template>
  <div class="container">
    <div class="row">
      <div class="col-lg-6 col-md-8 col-sm-12 mx-auto bg-color-ecru-white pt-4 px-0 books-list">
        <form class="d-flex align-items-center mb-4 px-4">
          <label class="flex-grow-1 mb-0 mr-2">
            <input placeholder="search" type="text" class="form-control">
          </label>
          <button type="submit" class="btn btn-primary text-white">Search</button>
        </form>
        <h1 class="text-primary text-center pb-2">Top books of all time</h1>
        <div v-for="i in books">{{i}}</div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
  import Vue from 'vue'

  export default Vue.extend({
    components: {
    },
    data: () => ({
      books: [1, 2, 3]
    })
  })
</script>

<style>

</style>

// q4/src/app/books/books.component.ts
import { Component, OnInit } from '@angular/core';

import { Book } from '../core/models/book';
import { PageSizeDefault } from '../core/models/paginator';
import { BooksService } from '../core/services/books.service';
import { ToastrService } from '../core/services/toastr.service';

@Component({
  selector: 'reedsy-books',
  templateUrl: './books.component.html',
  styleUrls: ['./books.component.scss']
})
export class BooksComponent implements OnInit {

  books: Book[] = [];
  total = 0;
  skip = 0;
  take = PageSizeDefault;

  isLoading = false;

  constructor(
    private booksService: BooksService,
    private toastrService: ToastrService,
  ) { }

  ngOnInit(): void {
    this.loadBooks();
  }

  async loadBooks() {
    try {
      this.isLoading = true;
      const res = await this.booksService.books(this.skip, this.take).toPromise();
      this.books = res.data;
      this.total = res.count;
    } catch (e) {
      this.toastrService.error(e, 'Failed to fetch books data.');
    } finally {
      this.isLoading = false;
    }
  }
}

<div class="container">
  <div class="row">
    <div class="col-lg-6 col-md-8 col-sm-12 mx-auto bg-color-ecru-white pt-4 px-0 books-list">
      <form class="d-flex align-items-center mb-4" [formGroup]="searchForm" (submit)="searchBooks($event)">
        <label class="flex-grow-1 mb-0 mr-2">
          <input placeholder="search" type="text" formControlName="keyword" class="form-control">
        </label>
        <button type="submit" [disabled]="!searchForm.valid" class="btn btn-primary text-white">Search</button>
      </form>
      <h1 class="text-primary text-center pb-2">Top books of all time</h1>
      <div class="text-center py-3" *ngIf="!books || books.length === 0">(No books)</div>
      <reedsy-book-card *ngFor="let book of books | paginate: {
        itemsPerPage: take,
        currentPage: page,
        totalItems: total
      }; let i=index" [book]="book" [index]="i + ( page - 1 ) * take">
      </reedsy-book-card>
      <div class="text-center pr-40">
        <pagination-controls (pageChange)="pageChange($event)"></pagination-controls>
      </div>
    </div>
  </div>
  <ngx-spinner bdColor="rgba(0, 0, 0, 0.8)" size="default" color="#fff" type="square-jelly-box" [fullScreen]="true">
    <p style="color: white">Loading...</p>
  </ngx-spinner>
</div>
